const RequestError = require("./RequestError");

/**
 * An error that occurs when a request times out because the server did not send a response within the specified timeout interval.
 */
class RetryError extends RequestError {
    constructor(url, request, originalError, message = `HTTP request [${request.name}] to ${url} was not successful after ${originalError.length} attempts.`) {
        super(url, request, originalError, message);
        this.name = "RetryError";
    }

    get retryErrors() {
        return this.originalError;
    }
}

module.exports = RetryError;